version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: users_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rakuten
      MYSQL_DATABASE: rakuten_db
#      MYSQL_USER: Olivier
#      MYSQL_PASSWORD: Olivier
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-data:/var/lib/mysql


  adminer:
    image: adminer
    container_name: admin_db
    restart: always
    ports:
      - "8080:8080"

  api_predict:
    build: 
      context: ./src
      dockerfile: Dockerfile.predict
    container_name: api_predict
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data

  api_oauth:
    build: 
      context: ./src/fastapi_oauth
      dockerfile: Dockerfile.oauth
    container_name: api_oauth
    restart: always
    ports:
      - "8001:8001"

  api_train:
    build: 
      context: ./src
      dockerfile: Dockerfile.train
    container_name: api_train
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
