apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./data/mysql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 600Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-models
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "./models"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-models
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "./data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-logs
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "./logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

