[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:nginx]
command=/usr/sbin/nginx -c /app/hf_deployment/nginx.conf -g "daemon off;"
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.out.log
stderr_logfile=/var/log/supervisor/nginx.err.log

[program:php-fpm]
command=/usr/sbin/php-fpm8.2 -F
autorestart=true
stdout_logfile=/var/log/supervisor/php-fpm.out.log
stderr_logfile=/var/log/supervisor/php-fpm.err.log

[program:mysql]
command=/usr/bin/mysqld_safe
autorestart=true
stdout_logfile=/var/log/supervisor/mysql.out.log
stderr_logfile=/var/log/supervisor/mysql.err.log

[program:airflow-webserver]
command=airflow webserver -p 8080
autorestart=true
stdout_logfile=/var/log/supervisor/airflow-webserver.out.log
stderr_logfile=/var/log/supervisor/airflow-webserver.err.log

[program:airflow-scheduler]
command=airflow scheduler
autorestart=true
stdout_logfile=/var/log/supervisor/airflow-scheduler.out.log
stderr_logfile=/var/log/supervisor/airflow-scheduler.err.log

[program:tensorboard]
command=tensorboard --logdir=/app/logs --port=6006 --path_prefix=/tensorboard --bind_all
autorestart=true
stdout_logfile=/var/log/supervisor/tensorboard.out.log
stderr_logfile=/var/log/supervisor/tensorboard.err.log

[program:api_predict]
command=uvicorn src.predict_API:app --host 0.0.0.0 --port 8000
directory=/app
autorestart=true
stdout_logfile=/var/log/supervisor/api_predict.out.log
stderr_logfile=/var/log/supervisor/api_predict.err.log

[program:api_oauth]
command=uvicorn src.fastapi_oauth.fastapi_oauth:app --host 0.0.0.0 --port 8001
directory=/app
autorestart=true
stdout_logfile=/var/log/supervisor/api_oauth.out.log
stderr_logfile=/var/log/supervisor/api_oauth.err.log

[program:api_train]
command=uvicorn src.main_API:app --host 0.0.0.0 --port 8002
directory=/app
autorestart=true
stdout_logfile=/var/log/supervisor/api_train.out.log
stderr_logfile=/var/log/supervisor/api_train.err.log

[program:api_flows]
command=uvicorn src.flows.flows_API:app --host 0.0.0.0 --port 8003
directory=/app
autorestart=true
stdout_logfile=/var/log/supervisor/api_flows.out.log
stderr_logfile=/var/log/supervisor/api_flows.err.log

[program:streamlit]
command=streamlit run streamlit_app/app_hf.py --server.port 8501 --server.address 0.0.0.0
directory=/app
autorestart=true
stdout_logfile=/var/log/supervisor/streamlit.out.log
stderr_logfile=/var/log/supervisor/streamlit.err.log
