FROM python:3.10.14-slim

# Create application directory
RUN mkdir -p /app
WORKDIR /app

# Copy the application code
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt || (echo "Failed to install dependencies" && exit 1)

# Expose port 8501 for Streamlit
EXPOSE 6006

WORKDIR /app

# Run the Streamlit app
CMD ["tensorboard", "--logdir=logs/", "--host=0.0.0.0"]

