FROM python:3.10.14-slim

# Installation de curl
RUN apt-get update && apt-get install -y curl

RUN mkdir -p /app/src
WORKDIR /app/src

# Copie du fichier requirements.txt séparément pour éviter de recopier tout le contenu si les dépendances n'ont pas changé
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

CMD ["uvicorn", "src.predict_API_docker:app", "--host", "0.0.0.0", "--port", "8000"]

